version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      gomod-backward-compatible:
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      github-actions-breaking:
        update-types:
          - "major"
      github-actions-backward-compatible:
        update-types:
          - "minor"
          - "patch"
