# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}.checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: yesdevnull
    name: tf-version-bump
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  header: |
    ## Installation

    To install `{{ .ProjectName }}`, download one of the pre-built binaries provided for your platform from the artifacts attached to this release.

    Pre-built binaries are provided for Linux, macOS, and Windows (amd64 and arm64 architectures).

    ### Quick Install (Linux amd64)

    ```bash
    # Download the binary
    curl -LO https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/{{ .ProjectName }}_{{ .Version }}_linux_x86_64.tar.gz

    # Extract
    tar -xzf {{ .ProjectName }}_{{ .Version }}_linux_x86_64.tar.gz

    # Move to PATH
    sudo mv {{ .ProjectName }} /usr/local/bin/

    # Make executable
    sudo chmod +x /usr/local/bin/{{ .ProjectName }}
    ```

    ### Verify binary integrity

    To verify the integrity of the downloaded binary, you can utilize the checksums file:

    ```bash
    # Download checksums
    curl -LO https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/{{ .ProjectName }}-v{{ .Version }}.checksums.txt

    # Verify the binary using the checksums file
    sha256sum -c {{ .ProjectName }}-v{{ .Version }}.checksums.txt --ignore-missing
    ```

    ### Verify artifact provenance

    This release includes [SLSA Level 3](https://slsa.dev/) provenance attestations for supply chain security. The SLSA provenance of the binaries and packages can be found within the artifacts associated with this release. It is presented through an [in-toto](https://in-toto.io/) link metadata file named `{{ .ProjectName }}-v{{ .Version }}.intoto.jsonl`.

    To verify the provenance of an artifact, you can utilize the [`slsa-verifier`](https://github.com/slsa-framework/slsa-verifier) tool:

    ```bash
    # Install slsa-verifier (if not already installed)
    go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@latest

    # Download the metadata file
    curl -LO https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/{{ .ProjectName }}-v{{ .Version }}.intoto.jsonl

    # Verify the provenance of the artifact
    slsa-verifier verify-artifact {{ .ProjectName }}_{{ .Version }}_linux_x86_64.tar.gz \
      --provenance-path {{ .ProjectName }}-v{{ .Version }}.intoto.jsonl \
      --source-uri github.com/{{ .Env.GITHUB_REPOSITORY }} \
      --source-tag {{ .Tag }}
    ```

    ### All Available Binaries

    See the **Assets** section below for binaries for all supported platforms:
    - **Linux**: `{{ .ProjectName }}_{{ .Version }}_linux_x86_64.tar.gz`, `{{ .ProjectName }}_{{ .Version }}_linux_arm64.tar.gz`
    - **macOS**: `{{ .ProjectName }}_{{ .Version }}_darwin_x86_64.tar.gz`, `{{ .ProjectName }}_{{ .Version }}_darwin_arm64.tar.gz`
    - **Windows**: `{{ .ProjectName }}_{{ .Version }}_windows_x86_64.zip`, `{{ .ProjectName }}_{{ .Version }}_windows_arm64.zip`
    - **Linux Packages**: `.deb` and `.rpm` packages for Debian/Ubuntu and RHEL/Fedora

    ### Alternative: Install via Go

    ```bash
    go install github.com/{{ .Env.GITHUB_REPOSITORY }}@{{ .Tag }}
    ```

nfpms:
  - package_name: tf-version-bump
    vendor: yesdevnull
    homepage: https://github.com/yesdevnull/tf-version-bump
    maintainer: yesdevnull
    description: CLI tool for updating Terraform module versions
    license: MIT
    formats:
      - deb
      - rpm
